### ISSUE TITLE
Add "firstNames" option

### ISSUE THREAD

**Issue by jfexyz** [theill/PawExtensions-NameRandomizerDynamicValue#1]
It would be nice to not have to specify a gender. How about a `firstNames` option that combines the two lists?

**Comment by theill** [comment]
Thanks for your request. You're welcome to make a PR for this but otherwise check out the Chance extension which now is available. Much more powerful than mine => https://luckymarmot.com/paw/extensions/com.atan.ChanceDynamicValue

**Comment by jfexyz** [comment]
Yep, already switched :)
